//! Generates `config.rs` with build-time constants.
//!
//! When built through meson, `CODEGEN_BUILD_DIR` points to a directory
//! containing a `config.rs` produced by `configure_file()`; we reuse it.
//! When built with plain `cargo` (tests, clippy, IDEs) sensible development
//! defaults are generated instead so the crate always compiles.

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    println!("cargo:rerun-if-env-changed=CODEGEN_BUILD_DIR");
    println!("cargo:rerun-if-changed=build.rs");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is set by cargo"));
    let dest = out_dir.join("config.rs");

    if let Ok(dir) = env::var("CODEGEN_BUILD_DIR") {
        let src = PathBuf::from(dir).join("config.rs");
        println!("cargo:rerun-if-changed={}", src.display());
        fs::copy(&src, &dest).unwrap_or_else(|e| panic!("cannot copy {}: {e}", src.display()));
        return;
    }

    let version = env::var("CARGO_PKG_VERSION").unwrap();
    let contents = format!(
        r#"// Generated by build.rs (development defaults; meson overrides these).
pub const APP_ID: &str = "io.github.talesam.Obscure.Devel";
pub const APP_VERSION: &str = "{version}";
pub const PROFILE: &str = "development";
pub const GETTEXT_PACKAGE: &str = "obscure";
pub const LOCALEDIR: &str = "/usr/share/locale";
pub const PKGDATADIR: &str = "/usr/share/obscure";
pub const BUILD_DATADIR: &str = "";
"#
    );
    fs::write(&dest, contents).expect("cannot write config.rs");
}
